---
- hosts: target1
  become: true
  tasks:
   - name: Install rabbitmq 
     shell:
       cmd: "{{ item }}"
     with_items:
      - wget -O - "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey" | sudo apt-key add -
      - apt-get update -y
      - apt-get install curl gnupg -y
      - curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | sudo apt-key add -
      - apt-get install apt-transport-https  
      
     ignore_errors: yes
   - name: add repo    
     apt_repository:
       repo: "{{ item }}"
       state: present
       filename: bintray.rabbitmq.list
     with_items:
      - deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang
      - deb https://dl.bintray.com/rabbitmq/debian bionic main 
     ignore_errors: yes
   - name: Run the following
     shell:
       cmd: "{{ item }}"
     with_items:
      - apt-get update -y
      - apt-get install rabbitmq-server -y --fix-missing
  #become: yes
